const PROJETOS_FALLBACK=[
 {id:'agroflux',titulo:'AgroFlux Gestão Agrícola',categoria:'Sistemas',data:'2026-05-12',imagem:'case-agro.jpg',descricao:'Operações, safras e indicadores reunidos em uma plataforma clara.',tecnologias:['HTML5','CSS Grid','JavaScript'],resultados:['32% menos retrabalho','2,4× mais agilidade','98% de adoção']},
 {id:'dashboard-financeiro',titulo:'Nexo Dashboard Financeiro',categoria:'UI/UX',data:'2026-03-20',imagem:'case-agro.jpg',descricao:'Painel executivo para decisões financeiras rápidas e auditáveis.',tecnologias:['UI/UX','JavaScript','Acessibilidade'],resultados:['41% menos tempo de análise','18 fluxos unificados','AA de contraste']},
 {id:'medagenda',titulo:'MedAgenda Clínica',categoria:'Sistemas',data:'2025-11-08',imagem:'case-agro.jpg',descricao:'Agendamento médico simples para pacientes e equipes clínicas.',tecnologias:['HTML5','JavaScript','Design System'],resultados:['27% menos faltas','4 unidades integradas','NPS 82']},
 {id:'urbano',titulo:'Urbano Mobilidade',categoria:'Automação',data:'2025-09-14',imagem:'case-mobilidade.jpg',descricao:'Jornadas digitais e alertas automáticos para transporte urbano.',tecnologias:['Automação','UX Research','JavaScript'],resultados:['60 mil usuários','22% mais retenção','15 rotinas automáticas']},
 {id:'serliv-academy',titulo:'Serliv Academy',categoria:'Sites',data:'2025-06-11',imagem:'c03.jpg',descricao:'Plataforma editorial para cursos e conteúdos profissionais.',tecnologias:['HTML5','CSS3','SEO'],resultados:['93 no Lighthouse','35% mais conversão','SEO estruturado']},
 {id:'orbit-launch',titulo:'Orbit Tech Launch',categoria:'Landing Pages',data:'2025-02-03',imagem:'c04.jpg',descricao:'Landing page de lançamento com narrativa orientada à conversão.',tecnologias:['Copy UX','Performance','Analytics'],resultados:['12,8% de conversão','1,1s de carregamento','3 testes A/B']},
 {id:'flowdesk',titulo:'FlowDesk Processos',categoria:'Automação',data:'2024-10-18',imagem:'c01.jpg',descricao:'Central de solicitações e automações para times operacionais.',tecnologias:['Automação','UX','JavaScript'],resultados:['420 h economizadas','9 fluxos digitais','Zero papel']},
 {id:'norte-institucional',titulo:'Norte Engenharia',categoria:'Sites',data:'2024-07-09',imagem:'c02.jpg',descricao:'Site corporativo rápido, acessível e fácil de manter.',tecnologias:['HTML5','CSS3','SEO'],resultados:['95 em desempenho','40% mais contatos','WCAG AA']}
];
(() => { const grades=document.querySelectorAll('[data-grade-projetos]'); if(!grades.length&&!document.querySelector('[data-detalhe-projeto]'))return; const base=window.Serliv?.prefixo||''; let lista=[...PROJETOS_FALLBACK], limite=6, categoria='Todos', termo='', ordem='data';
 const carregar=async()=>{try{const resposta=await fetch(base+'dados/projetos.json');if(resposta.ok)lista=await resposta.json()}catch(e){} renderizar(); carregarDetalhe()};
 const card=p=>`<article class="card projeto-card"><img class="card__imagem" src="${base}assets/imagens/${p.imagem}" alt="Interface do projeto ${p.titulo}"><div class="card__corpo"><span class="etiqueta">${p.categoria}</span><h3>${p.titulo}</h3><p class="muted">${p.descricao}</p><div class="card__tecnologias">${p.tecnologias.map(t=>`<span>${t}</span>`).join('')}</div><div class="acoes"><button class="botao botao--pequeno" data-modal-projeto="${p.id}">Visão rápida</button><a class="botao botao--secundario botao--pequeno" href="${base}pages/projeto.html?id=${p.id}">Detalhes</a></div></div></article>`;
 function filtrados(){return lista.filter(p=>(categoria==='Todos'||p.categoria===categoria)&&(`${p.titulo} ${p.descricao}`.toLowerCase().includes(termo))).sort((a,b)=>ordem==='nome'?a.titulo.localeCompare(b.titulo):b.data.localeCompare(a.data))}
 function renderizar(){const dados=filtrados();grades.forEach(g=>{g.innerHTML=dados.slice(0,g.dataset.gradeProjetos==='todos'?limite:6).map(card).join(''); const vazio=g.parentElement.querySelector('[data-vazio]');if(vazio)vazio.hidden=!!dados.length});document.querySelector('[data-carregar-mais]')?.toggleAttribute('hidden',dados.length<=limite);document.querySelectorAll('[data-modal-projeto]').forEach(b=>b.addEventListener('click',()=>abrirModal(b.dataset.modalProjeto)))}
 document.querySelectorAll('[data-filtro-projeto]').forEach(b=>b.addEventListener('click',()=>{categoria=b.dataset.filtroProjeto;document.querySelectorAll('[data-filtro-projeto]').forEach(x=>x.classList.toggle('ativo',x===b));limite=6;renderizar()}));document.querySelector('[data-pesquisa-projeto]')?.addEventListener('input',e=>{termo=e.target.value.toLowerCase().trim();renderizar()});document.querySelector('[data-ordem-projeto]')?.addEventListener('change',e=>{ordem=e.target.value;renderizar()});document.querySelector('[data-carregar-mais]')?.addEventListener('click',()=>{limite+=3;renderizar()});
 const modal=document.querySelector('[data-modal]');let focoAnterior;function fecharModal(){if(!modal)return;modal.classList.remove('aberto');document.body.classList.remove('sem-rolagem');focoAnterior?.focus()} function abrirModal(id){const p=lista.find(x=>x.id===id);if(!p||!modal)return;focoAnterior=document.activeElement;modal.querySelector('[data-modal-conteudo]').innerHTML=`<img class="modal__imagem" src="${base}assets/imagens/${p.imagem}" alt="${p.titulo}"><div class="modal__corpo"><span class="etiqueta">${p.categoria}</span><h2 id="modal-titulo">${p.titulo}</h2><p>${p.descricao}</p><div class="card__tecnologias">${p.tecnologias.map(t=>`<span>${t}</span>`).join('')}</div><a class="botao" href="${base}pages/projeto.html?id=${p.id}">Ver estudo de caso</a></div>`;modal.classList.add('aberto');document.body.classList.add('sem-rolagem');modal.querySelector('[data-fechar-modal]').focus()} modal?.querySelector('[data-fechar-modal]')?.addEventListener('click',fecharModal);modal?.addEventListener('click',e=>{if(e.target===modal)fecharModal()});document.addEventListener('keydown',e=>{if(e.key==='Escape')fecharModal();if(e.key==='Tab'&&modal?.classList.contains('aberto')){const focaveis=[...modal.querySelectorAll('button,a')];const primeiro=focaveis[0],ultimo=focaveis.at(-1);if(e.shiftKey&&document.activeElement===primeiro){e.preventDefault();ultimo.focus()}else if(!e.shiftKey&&document.activeElement===ultimo){e.preventDefault();primeiro.focus()}}});
 function carregarDetalhe(){const alvo=document.querySelector('[data-detalhe-projeto]');if(!alvo)return;const id=new URLSearchParams(location.search).get('id')||'dashboard-financeiro';const p=lista.find(x=>x.id===id)||lista[0];document.title=`${p.titulo} | Studio Serliv`;alvo.innerHTML=`<section class="pagina-topo"><div class="container"><span class="sobretitulo">${p.categoria}</span><h1 class="titulo-secao">${p.titulo}</h1><p>${p.descricao}</p></div></section><section class="secao"><div class="container case-hero"><div><span class="sobretitulo">Estudo de caso</span><h2 class="titulo-secao">Clareza para uma operação complexa</h2><p>O desafio era transformar processos dispersos em uma jornada digital eficiente, inclusiva e mensurável.</p><div class="tecnologias">${p.tecnologias.map(t=>`<span class="tecnologia">${t}</span>`).join('')}</div></div><img src="${base}assets/imagens/${p.imagem}" alt="Tela principal de ${p.titulo}"></div></section><section class="secao secao--suave"><div class="container grade grade--3"><article><h2>Contexto</h2><p>A equipe precisava crescer sem multiplicar tarefas manuais e pontos de falha.</p></article><article><h2>Problema</h2><p>Informações fragmentadas reduziam a confiança nos dados e atrasavam decisões.</p></article><article><h2>Solução</h2><p>Criamos uma interface modular, acessível e orientada às tarefas prioritárias.</p></article></div></section><section class="secao"><div class="container"><div class="secao__cabecalho"><span class="sobretitulo">Processo</span><h2 class="titulo-secao">Da descoberta à entrega</h2></div><div class="grade grade--3 processo"><article class="processo__item"><h3>Imersão</h3><p>Entrevistas e diagnóstico.</p></article><article class="processo__item"><h3>Prototipação</h3><p>Fluxos testados cedo.</p></article><article class="processo__item"><h3>Implementação</h3><p>Entrega incremental e QA.</p></article></div></div></section><section class="secao secao--suave resultados"><div class="container"><h2 class="titulo-secao">Resultados</h2><div class="grade grade--3">${p.resultados.map(r=>`<article class="card resultado"><strong>${r}</strong><p>Impacto observado após a implantação.</p></article>`).join('')}</div></div></section><section class="secao"><div class="container"><h2>Galeria do projeto</h2><div class="grade grade--2 galeria"><img src="${base}assets/imagens/case-agro.jpg" alt="Detalhe visual do projeto"><img src="${base}assets/imagens/case-agro.jpg" alt="Segunda composição visual do projeto"></div><div class="acoes"><a class="botao botao--secundario" href="projetos.html">← Voltar ao portfólio</a><a class="botao" href="projeto.html?id=${lista[(lista.indexOf(p)+1)%lista.length].id}">Próximo projeto →</a></div></div></section>`}
 carregar();
})();
